#!/usr/bin/env bash
# Start OpenTelemetry Demo (Astronomy Shop) bridged to SentinelLoop LGTM.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
DEMO_DIR="${ROOT}/third_party/opentelemetry-demo"
BRIDGE="${ROOT}/integrations/astronomy-shop/compose.aiops-bridge.yaml"
EXPORT_CFG="${ROOT}/integrations/astronomy-shop/otelcol-config-aiops-export.yml"
NET="aiops-demo-bedrock_aiops-net"

echo "==> Ensuring AIOps stack (LGTM + control plane)..."
cd "$ROOT"
docker compose -f docker-compose.yml -f docker-compose.astronomy.yml up -d --build \
  lgtm redis \
  aiops-anomaly-detector aiops-incident-manager aiops-rca-engine \
  aiops-decision-engine aiops-remediation aiops-feedback-collector \
  aiops-engine-qa aiops-console

if ! docker network ls --format '{{.Name}}' | grep -qx "$NET"; then
  echo "ERROR: network $NET missing" >&2
  exit 1
fi

if [[ ! -f "${DEMO_DIR}/compose.yaml" ]]; then
  echo "==> Cloning opentelemetry-demo (shallow)..."
  mkdir -p "${ROOT}/third_party"
  git clone --depth 1 https://github.com/open-telemetry/opentelemetry-demo.git "$DEMO_DIR"
fi

cp -f "$EXPORT_CFG" "${DEMO_DIR}/src/otel-collector/otelcol-config-aiops-export.yml"
cat > "${DEMO_DIR}/.env.override" <<'EOF'
# Generated by SentinelLoop scripts/astronomy/start.sh
OTEL_COLLECTOR_CONFIG_EXTRAS=./src/otel-collector/otelcol-config-aiops-export.yml
EOF

echo "==> Starting Astronomy Shop (no o11y UI — use AIOps LGTM)..."
cd "$DEMO_DIR"
docker compose --env-file .env --env-file .env.override \
  -f compose.yaml -f compose.extras.yaml \
  -f "$BRIDGE" \
  up -d --remove-orphans

echo ""
echo "Frontend:     http://localhost:8080"
echo "Flagd UI:     http://localhost:4000"
echo "Grafana LGTM: http://localhost:3000"
echo "Incidents:    http://localhost:8002"
echo "Fault inject: python scripts/astronomy/set_flag.py paymentFailure on"
