# Start OpenTelemetry Demo (Astronomy Shop) bridged to SentinelLoop LGTM.
# Prerequisites: Docker, git, AIOps stack already running (aiops-lgtm healthy).
#
# Usage (from repo root):
#   powershell -ExecutionPolicy Bypass -File scripts/astronomy/start.ps1

$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$DemoDir = Join-Path $Root "third_party\opentelemetry-demo"
$BridgeCompose = Join-Path $Root "integrations\astronomy-shop\compose.aiops-bridge.yaml"
$ExportCfg = Join-Path $Root "integrations\astronomy-shop\otelcol-config-aiops-export.yml"

Write-Host "==> SentinelLoop Astronomy Shop bridge" -ForegroundColor Cyan
Write-Host "Repo root: $Root"

# 1) Ensure AIOps network / LGTM
Write-Host "==> Ensuring AIOps stack (LGTM) is up..."
Push-Location $Root
docker compose -f docker-compose.yml -f docker-compose.astronomy.yml up -d --build lgtm redis
# AIOps control plane (no mini apps)
docker compose -f docker-compose.yml -f docker-compose.astronomy.yml up -d --build `
  aiops-anomaly-detector aiops-incident-manager aiops-rca-engine `
  aiops-decision-engine aiops-remediation aiops-feedback-collector `
  aiops-engine-qa aiops-console
Pop-Location

$net = "aiops-demo-bedrock_aiops-net"
$exists = docker network ls --format "{{.Name}}" | Select-String -SimpleMatch $net
if (-not $exists) {
  Write-Error "Docker network $net not found. Start AIOps compose first."
}

# 2) Clone demo (shallow)
if (-not (Test-Path (Join-Path $DemoDir "compose.yaml"))) {
  Write-Host "==> Cloning open-telemetry/opentelemetry-demo (shallow)..."
  New-Item -ItemType Directory -Force -Path (Join-Path $Root "third_party") | Out-Null
  git clone --depth 1 https://github.com/open-telemetry/opentelemetry-demo.git $DemoDir
} else {
  Write-Host "==> Demo repo already present: $DemoDir"
}

# 3) Install AIOps collector export extras
$extrasTarget = Join-Path $DemoDir "src\otel-collector\otelcol-config-aiops-export.yml"
Copy-Item -Force $ExportCfg $extrasTarget
Write-Host "==> Installed collector export config -> $extrasTarget"

# Patch .env.override for dual-write + avoid clobbering AIOps ports where possible
$override = Join-Path $DemoDir ".env.override"
$overrideBody = @"
# Generated by SentinelLoop scripts/astronomy/start.ps1
# Export demo telemetry into AIOps LGTM (collector extras file).
OTEL_COLLECTOR_CONFIG_EXTRAS=./src/otel-collector/otelcol-config-aiops-export.yml

# Avoid fighting SentinelLoop host ports (LGTM uses 3000/9090/4317/4318).
# Demo apps still use internal DNS; only published ports shift when set as host:container.
# Frontend proxy stays on 8080 if free; change if occupied:
# ENVOY_PORT=18080
"@
Set-Content -Path $override -Value $overrideBody -Encoding UTF8
Write-Host "==> Wrote $override"

# 4) Start Astronomy Shop WITHOUT its own Grafana/Prometheus/Jaeger stack
#    (start-minimal-no-o11y = core + extras, no compose.observability.yaml)
Write-Host "==> Starting Astronomy Shop (apps + collector, no o11y UI)..."
Push-Location $DemoDir
$env:OTEL_COLLECTOR_CONFIG_EXTRAS = "./src/otel-collector/otelcol-config-aiops-export.yml"
docker compose --env-file .env --env-file .env.override `
  -f compose.yaml -f compose.extras.yaml `
  -f $BridgeCompose `
  up -d --remove-orphans
Pop-Location

Write-Host ""
Write-Host "Done. Next steps:" -ForegroundColor Green
Write-Host "  1. Frontend (Astronomy Shop):  http://localhost:8080"
Write-Host "  2. Flagd UI (fault inject):    http://localhost:4000"
Write-Host "  3. Grafana LGTM (AIOps):       http://localhost:3000"
Write-Host "  4. Incident console:           http://localhost:8002"
Write-Host "  5. Inject fault:  py -3.11 scripts/astronomy/set_flag.py paymentFailure on"
Write-Host "  6. Topology:      config/service_topology_astronomy.yaml"
Write-Host ""
Write-Host "Stop demo only:  bash scripts/astronomy/stop.sh   (or stop.ps1)"
